import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./GlobalRedux/provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Loading from "./Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "YourLab",
  description: "Generated by YourLab IT ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Loading />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
